### ISSUE TITLE
some problems in the installation instructions, just to remind people who want to run the project with .sh files

### ISSUE THREAD

**Issue by hyperi0nW** [YutoShibata07/AcousticPose_Public#1]
in readme.md, it said:
Put MotionCapture data and sound data under data folder like below.
pose_estimation_with_noise/data/poses
pose_estimation_with_noise/data/sound
pose_estimation_with_noise/data/annotations

but if you r using shell that the author provided, u should put the entire "data" folder into the "scripts" folder

**Comment by Y-ying-ch** [comment]
打扰一下，我复现时遇到了代码问题。使用源码的.sh文件运行，但是在 File"E:\AcousticPose\pose_estimation_with_noise\scripts\libs\dataset.py", line 274, in __init__
    self.sound = self.sound.transpose(0, 2, 1) # [sample_size, channels, sound_length]
  ValueError: axes don't match array中间报错。
完整报错是：
- Error Encountered:
  ```
  Traceback (most recent call last):
  File "train.py", line 250, in <module>
    main()
  File "train.py", line 94, in main
    train_loader = get_dataloader(
  ...
  File "E:\AcousticPose\pose_estimation_with_noise\scripts\libs\dataset.py", line 274, in __init__
    self.sound = self.sound.transpose(0, 2, 1) # [sample_size, channels, sound_length]
  ValueError: axes don't match array
如果有时间可否帮我看一下这部分，谢谢！！！
